# Generated by Django 6.1 on 2026-08-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('shipping_address', models.TextField(verbose_name='Địa chỉ giao hàng')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('shipping', 'Đang giao'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('payment_method', models.CharField(default='cod', max_length=20, verbose_name='Phương thức thanh toán')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Tên sản phẩm tại thời điểm mua')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Đơn giá tại thời điểm mua')),
                ('quantity', models.PositiveIntegerField(verbose_name='Số lượng')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Đơn hàng')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product', verbose_name='Sản phẩm')),
            ],
        ),
    ]
